version: '3.1'

services:
    app:
        container_name: node-express-graphql
        restart: always
        build: .
        ports:
            - '4000:4000'
        environment:
            MONGO_URL: 'mongodb://mongodb:27017'
            MONGO_DB_NAME: 'testDB'
        volumes:
            - .:/src
        links:
            - mongodb
    mongodb:
        image: mongo:4.4.3-bionic
        volumes:
            - ./devops/db/mongo:/data/db
        ports:
            - 27017:27017
